sudo: required
dist: xenial
os: linux
language: minimal
services:
  - docker

install: make
script:
  - make up
  - make info
  - docker stats $(docker ps --format={{.Names}}) --no-stream
  - docker system df -v
  - make down
