sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  global:
    - VERSION=4.3.1
    - DOCKER_TAG=4.3.1
install: skip
script:
  - docker build --tag grantmacken/alpine-exist:${DOCKER_TAG} --build-arg VERSION=${VERSION} .
  - docker-compose up -d
  - docker ps
  - N=0;until curl -I -s -f 'http://127.0.0.1:8080/' | grep 'Jetty' || [ $N -eq 20 ]; do sleep $(( N++ )); done
  - docker logs ex
  - docker-compose down



