sudo: required
dist: trusty
os: linux
language: c
services:
  - docker

env:
  global:
    - DOCKER_IMAGE=grantmacken/alpine-exist
    - DOCKER_TAG=v4.4.0
    - VERSION=4.4.0
install: make
script:
  - make up
  - make down
