sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  - VERSION=4.3.1
  - DOCKER_TAG=4.3.1
install: skip
script:
  - docker build --tag  "grantmacken/alpine-exist:${DOCKER_TAG}" --build-arg "VERSION=${VERSION}" .
  - docker-compose up -d
  - docker ps -a | grep 'exist'
  - docker logs ex
  - docker-compose down

# - echo "${DOCKER_TAG}"
# - docker build --tag  "grantmacken/alpine-exist:${DOCKER_TAG}" .

# before_deploy:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# deploy:
#   provider: script
#   script: echo "${DOCKER_TAG}"
#   on:
#     branch: master
