sudo: required
dist: trusty
os: linux
language: c
services:
  - docker

before_install: mkdir -p tmp
install: make tmp/eXist-latest.version
script:
  - export DOCKER_TAG=base-v$(cat tmp/eXist-latest.version)

# - echo "${DOCKER_TAG}"
# - docker build --tag  "grantmacken/alpine-exist:${DOCKER_TAG}" .
# - docker-compose up -d
# - docker ps -a | grep 'exist'
# - docker logs ex
# - docker-compose down

# before_deploy:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# deploy:
#   provider: script
#   script: echo "${DOCKER_TAG}"
#   on:
#     branch: master
