sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  global:
    - DOCKER_TAG=dummy
  install: make build
script:
  - docker-compose up -d
  - docker ps -a | grep 'ex'
  - N=0;until curl -Isf http://127.0.0.1:8080/ | grep 'Jetty' || [ $N -eq 20 ]; do sleep $(( N++ )); done
  - curl -Is http://127.0.0.1:8080/ | grep 'Jetty'
  - docker logs ex | grep 'Server has started'
  - docker-compose down
