sudo: required
dist: trusty
os: linux
language: c
services:
  - docker

install: skip
script:
  - mkdir -p tmp
  - make tmp/eXist-latest.version
  - export DOCKER_TAG=base-v$(cat tmp/eXist-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
  - echo "${DOCKER_TAG}"
  - docker build --tag  "grantmacken/alpine-exist:${DOCKER_TAG}"
# - docker build --pull --cache-from "$IMAGE" --tag "$IMAGE" .
# - docker run --name ex --publish 8080:8080 -d $IMAGE
# - docker ps
# - docker exec ex pwd
# - docker exec ex which java
# - mkdir -p tmp
# - make tmp/openresty-latest.version
# - export DOCKER_TAG=base-v$(cat tmp/openresty-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
# - echo "${DOCKER_TAG}"
# - docker build --tag  "grantmacken/alpine-openresty:${DOCKER_TAG}" . >/dev/null 2>&1
# - docker-compose up -d
# - docker ps | grep ${DOCKER_TAG}
# - docker exec or ls .
# - docker exec or which resty
# - docker exec or which openresty

# before_deploy:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# deploy:
#   provider: script
#   script: echo "${DOCKER_TAG}"
#   on:
#     branch: master
