sudo: required
dist: trusty
os: linux
language: c
services:
  - docker

install: skip
script:
  - mkdir -p tmp
  - make tmp/eXist-latest.version
  - export DOCKER_TAG=base-v$(cat tmp/eXist-latest.version | grep -oP 'tag_name": "eXist(.+)\K([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')

  # - echo "${DOCKER_TAG}"
  # - docker build --tag  "grantmacken/alpine-exist:${DOCKER_TAG}" .
  # - docker-compose up -d
  # - docker ps -a | grep 'exist'
  # - docker logs ex
  # - docker-compose down

# before_deploy:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# deploy:
#   provider: script
#   script: echo "${DOCKER_TAG}"
#   on:
#     branch: master
