sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  global:
    - DOCKER_TAG=v4.3.1
    - URL='http://127.0.0.1:8080/'
  install: make build
script:
  - docker-compose up -d
  - docker ps -a | grep 'exist'
  - N=0;until curl -Isf $URL | grep 'Jetty' || [ $N -eq 20 ]; do sleep $(( N++ )); done
  - curl -Is $URL | grep 'Jetty'
  - docker logs exist | grep 'Server has started'
  - docker-compose down
