sudo: required
dist: trusty
os: linux
language: c
services:
  - docker

install: skip
script:
  - mkdir -p tmp
  - make tmp/eXist-latest.version
  - export DOCKER_TAG=base-v$(cat tmp/eXist-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
  - echo "${DOCKER_TAG}"
  - docker build --tag  "grantmacken/alpine-exist:${DOCKER_TAG}" .
  - docker-compose up -d
  - docker ps -a | grep 'exist'
  - while [[ -z "$(curl -I -s -f 'http://127.0.0.1:8080/')" ]] ; do sleep 10 ; done
  - curl -Is http://127.0.0.1:8080/ | grep 'Jetty'
  - docker logs exist | grep 'Server has started'
  - docker-compose down

# before_deploy:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# deploy:
#   provider: script
#   script: echo "${DOCKER_TAG}"
#   on:
#     branch: master
