name: eXist builds
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: fetch exist distribution
        run: make fetch
      - name: build from alpine image
        run: make build
      - name: check running instance
        run: make run
          # podman images
        # uses: docker/login-action@v1
        # with:
        #   registry: ghcr.io
        #   username: ${{ github.actor }}
        #   password: ${{ secrets.GITHUB_TOKEN }}
